import Head from "next/head";
import React, { useState, useEffect } from "react";
import LeftSideBar from "../../components/LeftSideBar/LeftSideBar";
import MainLayout from "../../components/MainLayOut/MainLayout";
import RightSideBar from "../../components/RightSideBar/RightSiderBar";
import TopBar from "../../components/TopBar/TopBar";
import Section from "../../components/Section/Section";

export default function Home() {
  const [isLeftBarOpen, setLeftBarOpen] = useState(false);
  const [isRightBarOpen, setRightBarOpen] = useState(false);

  const toggleLeftBar = () => {
    if (!isRightBarOpen) {
      setLeftBarOpen(!isLeftBarOpen);
    } else {
      setRightBarOpen(false);
      setLeftBarOpen(true);
    }
  };

  const toggleRightBar = () => {
    if (!isLeftBarOpen) {
      setRightBarOpen(!isRightBarOpen);
    } else {
      setLeftBarOpen(false);
      setRightBarOpen(true);
    }
  };

  return (
    <>
      <Head>
        <title>Zyear Book</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <TopBar toggleLeftBar={toggleLeftBar} toggleRightBar={toggleRightBar} />
        <LeftSideBar isLeftBarOpen={isLeftBarOpen} />
        <Section />
        <RightSideBar isRightBarOpen={isRightBarOpen} />
      </MainLayout>
    </>
  );
}
