import Head from "next/head";
import React, { useState, useEffect } from "react";
import LeftSideBar from "../../components/LeftSideBar/LeftSideBar";
import MainLayout from "../../components/MainLayOut/MainLayout";
import RightSideBar from "../../components/RightSideBar/RightSiderBar";
import TopBar from "../../components/TopBar/TopBar";
import Section from "../../components/Section/Section";
import { AppProvider } from "../../components/Context/AppContext";

export default function Home() {
  return (
    <>
      <Head>
        <title>Zyear Book</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppProvider>
        <MainLayout>
          <TopBar />
          <LeftSideBar />
          <Section />
          <RightSideBar />
        </MainLayout>
      </AppProvider>
    </>
  );
}
